// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsdwdeigzxvchfdamhuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZHdkZWlnenh2Y2hmZGFtaHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDk2ODUsImV4cCI6MjA2OTAyNTY4NX0.HHB-l3nIefb8C9QyP09ldyxeDCLJRcFBPqqdJ992kso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});